apiVersion: apps/v1
kind: Deployment
metadata:
  name: pwc-microservice-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pwc-microservice
  template:
    metadata:
      labels:
        app: pwc-microservice
    spec:
      containers:
      - name: pwc-microservice
        image: pwc-microservice:latest
        ports:
        - containerPort: 5000
