apiVersion: v1
kind: Service
metadata:
  name: pwc-microservice-service
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "false"
spec:
  type: LoadBalancer
  ports:
  - port: 80          # Port to access externally
    targetPort: 5000   # Port your Flask app listens on
  selector:
    app: pwc-microservice
